pipeline { 
    agent any 
    tools { 
        maven 'Maven'  
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test
            }
        }
        stage('Deliver') {
            when {
                expression {
                    BRANCH_NAME == 'main'
                }
            }
            steps {
                sh 'chmod +x ./jenkins/scripts/deliver.sh'
                sh 'mvn package'
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
